spring.application.name=auth-service

server.port= 8080

spring.datasource.url=jdbc:mysql://localhost:3306/freemarket_auth?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

eureka.client.register-with-eureka= true
eureka.client.fetch-registry= true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/



# Tipo de ventana para contar fallos:
# COUNT_BASED = evalúa por número de llamadas
# TIME_BASED  = evalúa por tiempo (ej: últimos 60 segundos)
resilience4j.circuitbreaker.instances.auhtService.sliding-window-type=COUNT_BASED

# Tamaño de la ventana: evalúa las últimas 10 llamadas para
# decidir si el circuito debe abrirse o no
resilience4j.circuitbreaker.instances.auhtService.sliding-window-size=10

# Porcentaje de fallos para ABRIR el circuito:
resilience4j.circuitbreaker.instances.auhtService.failure-rate-threshold=50

# Tiempo que el circuito permanece ABIERTO antes de pasar a
# HALF_OPEN y probar si el servicio ya se recuperó
resilience4j.circuitbreaker.instances.auhtService.wait-duration-in-open-state=10s

# Número de llamadas de prueba permitidas en estado HALF_OPEN
# Si estas 3 llamadas son exitosas, el circuito vuelve a CLOSED
resilience4j.circuitbreaker.instances.auhtService.permitted-number-of-calls-in-half-open-state=3

# Registra el estado del circuit breaker en el Actuator (/actuator/health)
# para poder monitorearlo (CLOSED, OPEN, HALF_OPEN)
resilience4j.circuitbreaker.instances.auhtService.register-health-indicator=true

# ============================================================
# TIMEOUT 
# ============================================================

# Tiempo máximo de espera para la llamada al servicio externo.
# Si supera 3 segundos, lanza TimeoutException y va al fallback
resilience4j.timelimiter.instances.auhtService.timeout-duration=3s

# Si el timeout se cumple, cancela el Future que está corriendo
# en segundo plano (libera el hilo inmediatamente)
resilience4j.timelimiter.instances.auhtService.cancel-running-future=true

# ============================================================
# ACTUATOR - Monitoreo del estado de los patrones
# ============================================================

# GET /actuator/health
# GET /actuator/circuitbreakers
management.endpoints.web.exposure.include=health,circuitbreakers

# Incluye el estado del circuit breaker dentro del /actuator/health
# Mostrará CLOSED, OPEN o HALF_OPEN por cada instancia
management.health.circuitbreakers.enabled=true