spring.application.name=privileges-service

server.port= 8082

spring.datasource.url=jdbc:mysql://localhost:3306/freemarket_privileges?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

eureka.client.register-with-eureka= true
eureka.client.fetch-registry= true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

springdoc.swagger-ui.path=/privileges-swagger-ui

springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.doc-expansion=none


# ============================================================
# FEIGN + CIRCUIT BREAKER
# ============================================================
spring.cloud.openfeign.circuitbreaker.enabled=true
spring.cloud.openfeign.circuitbreaker.group.enabled=true   
spring.cloud.openfeign.client.config.auth-service.connect-timeout=5000
spring.cloud.openfeign.client.config.auth-service.read-timeout=5000

#time limiter 
resilience4j.circuitbreaker.instances.auth-service.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.timelimiter.instances.auth-service.timeout-duration=10s
resilience4j.timelimiter.instances.auth-service.cancel-running-future=true

# ============================================================
# RESILIENCE4J - Circuit Breaker
# ============================================================
resilience4j.circuitbreaker.instances.auth-service.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.auth-service.sliding-window-size=10
resilience4j.circuitbreaker.instances.auth-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.auth-service.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.auth-service.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.auth-service.register-health-indicator=true


# ============================================================
# ACTUATOR
# ============================================================
management.endpoints.web.exposure.include=health,circuitbreakers
management.health.circuitbreakers.enabled=true
